---
title: "Group Project - Written Analysis"
author: "Tseegi Nyamdorj, Tina Chang, Jinwen Xiang, My My Tran"
date: '2023-03-05'
output: 
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: yes
    fig_width: 7
    fig_height: 6
    fig_caption: yes
    theme: lumen
    df_print: paged
    code_folding: show
---
```{r}
library(ipumsr)
library(Stat2Data)
library(ggplot2)
library(dplyr)
library(moderndive) 
```

```{r}
# NOTE: To load data, you must download both the extract's data and the DDI
# and also set the working directory to the folder with these files (or change the path below).

if (!require("ipumsr")) stop("Reading IPUMS data into R requires the ipumsr package. It can be installed using the following command: install.packages('ipumsr')")

ddi <- read_ipums_ddi("highered_00002.xml")
data <- read_ipums_micro(ddi)
```

```{r}
data <- data[,!names(data) %in% c("WEIGHT", "SAMPLE", "SURID")]
```

```{r}
data_6years <- data %>%
  mutate(last06 = case_when(MR03Y5 >= 2006 | ACFPT == 1 | ACFPT == 2 ~ 1, 
                            MR03Y5 < 2006 | ACFPT == 98 | ACFPT == 3 ~ 0)) %>%
  mutate(chU6 = case_when(CH6IN == 0 | CH6IN == 98 ~ 0,
                          CH6IN == 1 ~ 1)) %>%
  mutate(GENDER = GENDER -1)
```
```{r}
data_6years$CHTOT <- factor(data_6years$CHTOT,
                       levels = c(98, 1,3),
                       labels = c("No Child", "One Child", "2 or More Children")
                       )
```

```{r}
model_6years <- glm( last06 ~ AGE + CHTOT, data = data_6years, family = binomial)
summary(model_6years)
```
```{r}
probabilities <- model_6years %>% 
  predict(data_6years, type = "response")
predicted.classes <- ifelse(probabilities> 0.5, 0, 1)
mean(predicted.classes == data_6years$last06)
```
```{r}
new_data1 <- exp(cbind(OR = coef(model_6years), confint(model_6years)))
head(new_data1)

```

```{r}
data_6years %>%
  ggplot(aes(x=AGE, y=last06, color= CHTOT)) +
  geom_point(
    position=position_jitter(height=.01)
    ) +
  geom_smooth(
    method=glm,
    method.args=list(family=binomial),
    se=FALSE,
    formula = y~x
    )
```

